# select the previous build image with known working MSYS2
# os: Previous Visual Studio 2015

version: 1.0.{build}
platform: x64
clone_folder: c:\project\src\minebot
#clone_depth: 5

build_script:
- cmd: >-
    cd c:\project\src\minebot\Minebot

    gradlew.bat build

#after_build:

cache:
  - c:\Users\appveyor\.gradle -> Minebot\build.gradle
  - c:\Users\appveyor\.m2 -> Minebot\build.gradle

artifacts:
  - path: Minebot\build\libs\minebot-rakslice-tooltweaks-1.11-13.19.1.2189.jar
    name: Minebot mod
  - path: Minebot\build\libs\minebot-rakslice-tooltweaks-1.11-13.19.1.2189-sources.jar
    name: Minebot source code
